# Puerto del Servidor gRPC (donde escuchará llamadas del Gateway en Python)
grpc.server.port=50051

# Puerto HTTP del Microservicio
server.port=8082

# Configuración de Base de Datos MySQL (Base desacoplada para Vehículos)
spring.datasource.url=jdbc:mysql://localhost:3306/rentar_vehiculos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
