type Query {
    reservas(filtro: FiltroReservaInput): [Reserva]
    consultarDisponibilidad(
        fechaInicio: String!
        fechaFin: String!
        tipo: TipoVehiculo
        marca: String
        modelo: String
        precioMin: Float
        precioMax: Float
    ): [Vehiculo]
    historialAlquileres(clienteId: ID!): [HistorialReserva]
    #devuelve el historial completo de alquileres de un cliente específico mediante el ID.
}

input FiltroReservaInput {
    clienteId: ID
    vehiculoId: ID
    tipo: TipoVehiculo
    estado: EstadoReserva
    fechaInicioDesde: String
    fechaInicioHasta: String
}

enum EstadoReserva {
    CONFIRMADA
    EN_CURSO
    CANCELADA
    FINALIZADA
}

enum TipoVehiculo {
    SEDAN
    SUV
    PICKUP
    COUPE
    HATCHBACK
}

enum EstadoVehiculo {
    DISPONIBLE
    RESERVADO
    EN_ALQUILER
}

type Reserva {
    id: ID!
    cliente: Cliente!
    vehiculo: Vehiculo!
    fechaInicio: String!
    fechaFin: String!
    precioDiario: Float!
    importeTotal: Float!
    estado: EstadoReserva!
}

type Cliente {
    id: ID!
    documento: String!
    nombre: String!
    apellido: String!
    email: String!
    telefono: String
    fechaNacimiento: String
    activo: Boolean!
    esAdmin: Boolean!
}

type Vehiculo {
    id: ID!
    patente: String!
    marca: String!
    modelo: String!
    anio: Int!
    color: String
    tipo: TipoVehiculo
    precioDiario: Float!
    estado: EstadoVehiculo!
    activo: Boolean!
}


type HistorialReserva {             #detalle de un alquiler o reserva pasada, incluyendo finalizados y cancelados.
    vehiculo: String!
    patente: String!
    fechaInicio: String!
    fechaFin: String!
    cantidadDias: Int!
    importeTotal: Float!
    estado: String!
}