type Vehiculo {
    patente: String!                #el ! significa que es obligatorio 
    marca: String!
    modelo: String!
    anio: Int!
    color: String
    tipo: String!
    precioDiario: Float!
}

type Query {
    consultarDisponibilidad(
        fechaInicio: String!
        fechaFin: String!
        tipo: String
        marca: String
        modelo: String
        precioMin: Float
        precioMax: Float
    ): [Vehiculo]
    historialAlquileres(clienteId: ID!): [HistorialReserva]     #devuelve el historial completo de alquileres de un cliente específico mediante el ID.
}

type HistorialReserva {             #detalle de un alquiler o reserva pasada, incluyendo finalizados y cancelados.
    vehiculo: String!
    patente: String!
    fechaInicio: String!
    fechaFin: String!
    cantidadDias: Int!
    importeTotal: Float!
    estado: String!
}