# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import vehicle_pb2 as proto_dot_vehicle__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/vehicle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListVehicles = channel.unary_unary(
                '/rentar.vehicle.v1.VehicleService/ListVehicles',
                request_serializer=proto_dot_vehicle__pb2.ListVehiclesRequest.SerializeToString,
                response_deserializer=proto_dot_vehicle__pb2.ListVehiclesResponse.FromString,
                _registered_method=True)
        self.CreateVehicle = channel.unary_unary(
                '/rentar.vehicle.v1.VehicleService/CreateVehicle',
                request_serializer=proto_dot_vehicle__pb2.CreateVehicleRequest.SerializeToString,
                response_deserializer=proto_dot_vehicle__pb2.Vehicle.FromString,
                _registered_method=True)
        self.GetVehicle = channel.unary_unary(
                '/rentar.vehicle.v1.VehicleService/GetVehicle',
                request_serializer=proto_dot_vehicle__pb2.GetVehicleRequest.SerializeToString,
                response_deserializer=proto_dot_vehicle__pb2.Vehicle.FromString,
                _registered_method=True)
        self.DeleteVehicle = channel.unary_unary(
                '/rentar.vehicle.v1.VehicleService/DeleteVehicle',
                request_serializer=proto_dot_vehicle__pb2.DeleteVehicleRequest.SerializeToString,
                response_deserializer=proto_dot_vehicle__pb2.DeleteVehicleResponse.FromString,
                _registered_method=True)


class VehicleServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListVehicles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListVehicles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVehicles,
                    request_deserializer=proto_dot_vehicle__pb2.ListVehiclesRequest.FromString,
                    response_serializer=proto_dot_vehicle__pb2.ListVehiclesResponse.SerializeToString,
            ),
            'CreateVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVehicle,
                    request_deserializer=proto_dot_vehicle__pb2.CreateVehicleRequest.FromString,
                    response_serializer=proto_dot_vehicle__pb2.Vehicle.SerializeToString,
            ),
            'GetVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicle,
                    request_deserializer=proto_dot_vehicle__pb2.GetVehicleRequest.FromString,
                    response_serializer=proto_dot_vehicle__pb2.Vehicle.SerializeToString,
            ),
            'DeleteVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVehicle,
                    request_deserializer=proto_dot_vehicle__pb2.DeleteVehicleRequest.FromString,
                    response_serializer=proto_dot_vehicle__pb2.DeleteVehicleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rentar.vehicle.v1.VehicleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rentar.vehicle.v1.VehicleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListVehicles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.vehicle.v1.VehicleService/ListVehicles',
            proto_dot_vehicle__pb2.ListVehiclesRequest.SerializeToString,
            proto_dot_vehicle__pb2.ListVehiclesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.vehicle.v1.VehicleService/CreateVehicle',
            proto_dot_vehicle__pb2.CreateVehicleRequest.SerializeToString,
            proto_dot_vehicle__pb2.Vehicle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.vehicle.v1.VehicleService/GetVehicle',
            proto_dot_vehicle__pb2.GetVehicleRequest.SerializeToString,
            proto_dot_vehicle__pb2.Vehicle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rentar.vehicle.v1.VehicleService/DeleteVehicle',
            proto_dot_vehicle__pb2.DeleteVehicleRequest.SerializeToString,
            proto_dot_vehicle__pb2.DeleteVehicleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
